export const PLAYBACK_QUEUE_ADD_TRACK = 'PLAYBACK_QUEUE_ADD_TRACK';
export const PLAYBACK_QUEUE_CLEAR_QUEUE = 'PLAYBACK_QUEUE_CLEAR_QUEUE';
export const PLAYBACK_QUEUE_DELETE_TRACK = 'PLAYBACK_QUEUE_DELETE_TRACK';
