export const ACCOUNT_MODAL_SET_AUTHENICATED = 'ACCOUNT_MODAL_SET_AUTHENICATED';
export const ACCOUNT_MODAL_SET_LOADER = 'ACCOUNT_MODAL_SET_LOADER';
export const ACCOUNT_MODAL_SET_VISIBILITY = 'ACCOUNT_MODAL_SET_VISIBILITY';
