export const ACCOUNT_MODAL_SET_ACCOUNT = 'ACCOUNT_MODAL_SET_ACCOUNT';
export const ACCOUNT_MODAL_SET_AUTHENICATED = 'ACCOUNT_MODAL_SET_AUTHENICATED';
export const ACCOUNT_MODAL_SET_ERROR = 'ACCOUNT_MODAL_SET_ERROR';
export const ACCOUNT_MODAL_SET_LOADING = 'ACCOUNT_MODAL_SET_LOADING';
export const ACCOUNT_MODAL_SET_VISIBILITY = 'ACCOUNT_MODAL_SET_VISIBILITY';
export const ACCOUNT_MODAL_SIGN_IN = 'ACCOUNT_MODAL_SIGN_IN';
export const ACCOUNT_MODAL_SIGN_OUT = 'ACCOUNT_MODAL_SIGN_OUT';
