export const PLAYLIST_ADD_MULTIPLE_TRACKS = 'PLAYLIST_ADD_MULTIPLE_TRACKS';
export const PLAYLIST_ADD_TRACK = 'PLAYLIST_ADD_TRACK';
export const PLAYLIST_CLEAR_PLAYLIST = 'PLAYLIST_CLEAR_PLAYLIST';
export const PLAYLIST_DELETE_TRACK = 'PLAYLIST_DELETE_TRACK';
