export const TRACK_CLEAR_TRACK = 'TRACK_CLEAR_TRACK';
export const TRACK_SET_MUTED = 'TRACK_SET_MUTED';
export const TRACK_SET_TRACK = 'TRACK_SET_TRACK';
export const TRACK_SET_VOLUME = 'TRACK_SET_VOLUME';
